name: CI
on: push
jobs:
  build:

  # Installs Yarn (npm alternative) to run jest tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test
    
  # Code Coverage Report
    - name: Create Coverage
      run: node ./node_modules/jest/bin/jest.js --coverage

    - name: Coveralls- post coverage report
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

  # Autogenerate jsDocs and output files to ./jsdocs
    - name: Generate jsDocs
      uses: andstor/jsdoc-action@v1
      with:
        source_dir:  ./source/scripts
        recurse: true
        output_dir:  ./jsdocs

  # Push generated files onto a new branch called gh-pages     
    - name: Deploy jsDocs
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./jsdocs
        external_repository: akanksha-maker-ucsd/jsDocs

  # Validate HTML and CSS
    - name: HTML5 Validator
      uses: Cyb3r-Jak3/html5validator-action@v7.2.0
      with:
        root: source/
        css: true
        
