name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test

    - name: Build
      uses: andstor/jsdoc-action@v1.2.1
      with:
        source_dir: ./source/scripts
        recurse: true
        output_dir: ./out
        template: minami
        front_page: README.md
    - name: Upload artifact from jsDos generation
      uses: actions/upload-artifact@v2
      with:
        name: jsdocs
        path: ./jsdocs
    - name: Deploy JSDocs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./jsdocs

    - name: HTML5 Validator
      uses: Cyb3r-Jak3/html5validator-action@v7.2.0
      with:
        root: source/
        css: true
        
