name: CI
on: push
jobs:
  build:

  # Installs Yarn (npm alternative) to run jest tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test
    
  # Code Coverage Report
    - name: Create Coverage
      run: node ./node_modules/jest/bin/jest.js --coverage >> coverage.txt

    - name: Coveralls- post coverage report
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

  # Autogenerate jsDocs and output files to ./jsdocs
    - name: Generate jsDocs
      uses: andstor/jsdoc-action@v1
      with:
        source_dir:  ./source/scripts
        recurse: true
        output_dir:  ./jsdocs

  # Push generated files onto a new branch called gh-pages     
    - name: Deploy jsDocs
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./jsdocs
        external_repository: akanksha-maker-ucsd/jsDocs

  # Validate HTML and CSS
    - name: HTML5 Validator
      uses: Cyb3r-Jak3/html5validator-action@v7.2.0
      with:
        root: source/
        css: true
        
    - name: Jest Coverage Comment
      id: coverageComment
      uses: MishaKav/jest-coverage-comment@main
      with:
        hide-comment: true
        coverage-path: ./coverage.txt

    - name: Check the output coverage
      run: |
        echo "Summary Report"
        echo "Coverage Percentage - ${{ steps.coverageComment.outputs.coverage }}"
        echo "Coverage Color - ${{ steps.coverageComment.outputs.color }}"
        echo "Summary Html - ${{ steps.coverageComment.outputs.summaryHtml }}"
          echo "JUnit Report"
          echo "tests - ${{ steps.coverageComment.outputs.tests }}"
          echo "skipped - ${{ steps.coverageComment.outputs.skipped }}"
          echo "failures - ${{ steps.coverageComment.outputs.failures }}"
          echo "errors - ${{ steps.coverageComment.outputs.errors }}"
          echo "time - ${{ steps.coverageComment.outputs.time }}"
          echo "Coverage Report"
          echo "lines - ${{ steps.coverageComment.outputs.lines }}"
          echo "branches - ${{ steps.coverageComment.outputs.branches }}"
          echo "functions - ${{ steps.coverageComment.outputs.functions }}"
          echo "statements - ${{ steps.coverageComment.outputs.statements }}"
          echo "coverage - ${{ steps.coverageComment.outputs.coverage }}"
          echo "color - ${{ steps.coverageComment.outputs.color }}"
          echo "Coverage Html - ${{ steps.coverageComment.outputs.coverageHtml }}"
    - name: Create the badge
      if: github.ref == 'refs/heads/main'
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.JEST_COVERAGE_COMMENT }}
        gistID: 5e90d640f8c212ab7bbac38f72323f80
        filename: jest-coverage-comment__main.json
        label: coverage
        message: ${{ steps.coverageComment.outputs.coverage }}%
        color: ${{ steps.coverageComment.outputs.color }}
        namedLogo: javascript  
