name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test
    
    - name: Create Coverage
      run: node ./node_modules/jest/bin/jest.js --coverage

    - name: Coveralls- post coverage report
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build jsDocs 
      uses: andstor/jsdoc-action@v1.2.1
      with:
        source_dir: ./source/scripts
        recurse: true
        output_dir: ./jsdocs
        template: minami
        front_page: README.md

    # - name: Upload artifact from jsdoc generation
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: jsdocs
    #     path: ./jsdocs
      
    # - name: Deploy
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    #     publish_dir: ./jsdocs

    - name: HTML5 Validator
      uses: Cyb3r-Jak3/html5validator-action@v7.2.0
      with:
        root: source/
        css: true
        
